// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Collections.ParallelSeq")>]
[<assembly: AssemblyProductAttribute("FSharp.Collections.ParallelSeq")>]
[<assembly: AssemblyDescriptionAttribute("Parallel sequence operators for F#.")>]
[<assembly: AssemblyVersionAttribute("1.1.2")>]
[<assembly: AssemblyFileVersionAttribute("1.1.2")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "FSharp.Collections.ParallelSeq"

    [<Literal>]
    let AssemblyProduct = "FSharp.Collections.ParallelSeq"

    [<Literal>]
    let AssemblyDescription = "Parallel sequence operators for F#."

    [<Literal>]
    let AssemblyVersion = "1.1.2"

    [<Literal>]
    let AssemblyFileVersion = "1.1.2"
