name: Build and Publish
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.401'
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore
      run: dotnet restore
    - name: Build (debug)
      run: dotnet build 
    - name: Test (debug)
      run: dotnet test
    - name: Build (release)
      run: dotnet build -c Release
    - name: Test (release)
      run: dotnet test -c Release
    - name: Pack (release)
      run: dotnet pack -c Release
    - name: Build docs
      run: dotnet fsdocs build --strict
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
    - name: Examine bin
      run: ls -r bin
    - name: Publish NuGets (if this version not published before)
      run: dotnet nuget push src/FSharp.Collections.ParallelSeq/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_ORG_TOKEN_2021 }} --skip-duplicate

# NUGET_ORG_TOKEN_2021 is listed in "Repository secrets" in https://github.com/fsprojects/FSharp.Collections.ParallelSeq/settings/secrets/actions
# note, the nuget org token expires around 06 October 2022
