name: Build and Test Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.401'
    - name: Install tools
      run: dotnet tool restore
    - name: Restore Build Test (debug)
      run: dotnet test 
    - name: Restore Build Test (release)
      run: dotnet test -c Release
    - name: Build docs
      run: dotnet fsdocs build --strict --properties Configuration=Release
